Tensors are multidimensional arrays. Here we have a collection of methods and properties that are really useful when we're working with them.

In [20]:
import tensorflow as tf

# Zero Dimensional Tensor
tensor_zero_d = tf.constant(4)
print(str(tensor_zero_d.ndim) + " Dimensions")

# 1 Dimensional Tensor
tensor_one_d = tf.constant([1, -5, 4])
print(str(tensor_one_d.ndim) + " Dimensions")


# 2 Dimensional Tensor
tensor_2d = tf.constant([[1, -5, 4], [1, 2, 0]])
print(str(tensor_2d.ndim) + " Dimensions")

# 3 Dimensional Tensor
tensor_3d = tf.constant([[[1, -5, 4], [1, 2, 0]], [[1, -5, 4], [1, 2, 0]]])
print(str(tensor_3d.ndim) + " Dimensions")



0 Dimensions
1 Dimensions
2 Dimensions
3 Dimensions


In [21]:
# 1D Tensor with a specific type
tensor_one_d_floats = tf.constant([1.18, -5.5, 4.3], dtype=tf.float32)
print(tensor_one_d_floats)

# Is possible to cast a tensor frome one type to another
casted_tensor = tf.cast(tensor_one_d, tf.int32)
print(casted_tensor)

# Even non-numeric values like boolean or string types are available
tensor_one_d_string = tf.constant(["hello","world"])
print(tensor_one_d_string)


tf.Tensor([ 1.18 -5.5   4.3 ], shape=(3,), dtype=float32)
tf.Tensor([ 1 -5  4], shape=(3,), dtype=int32)
tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)


In [22]:
import numpy as np

# Is possible to convert np arrays to tensors
np_arr = np.array([1, 2, 3])
nparr_to_tensor = tf.convert_to_tensor(np_arr)

print(type(np_arr))
print(nparr_to_tensor)

<class 'numpy.ndarray'>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [23]:
# tf.eye  Allows us to construct an identity matrix, 
# or a batch of matrices.  More info:
# https://www.tensorflow.org/api_docs/python/tf/eye

eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)


tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [24]:
# tf.fill Creates a tensor filled with a scalar value. 
# More info:
# https://www.tensorflow.org/api_docs/python/tf/fill

scalar_tensor = tf.fill(dims=[3,4], value=5, name=None)

print(scalar_tensor)


tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [25]:
# tf.ones Creates a tensor filled with a scalar value. 
# More info:
# https://www.tensorflow.org/api_docs/python/tf/ones

ones_tensor = tf.ones(
    shape=[5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [26]:
# tf.oneslike Creates a tensor of all ones that has the same shape as the input.
# More info:
# https://www.tensorflow.org/api_docs/python/tf/ones_like

input_tensor = tf.constant([[1,2,3],
                            [3,4,5]])

print(input_tensor)

ones_like_tensor = tf.ones_like(
    input_tensor, dtype=tf.dtypes.float32, name=None
)

print(ones_like_tensor)
print("shapes:", input_tensor.shape, ones_like_tensor.shape)

tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
shapes: (2, 3) (2, 3)


In [27]:
# rank, shape and size returns different constant aspects related to the tensor.


t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])

# Rank -> Returns a 0-D int32 Tensor representing the rank of input.
print(tf.rank(t)) # 3

# Shape -> Returns a 1-D integer tensor representing the shape of input.
print(tf.shape(t)) # [2 2 3]

# Size -> Returns a 0-D Tensor representing the number of 
# elements in input of type out_type.
print(tf.size(t)) # 12



tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([2 2 3], shape=(3,), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)


In [28]:
# random.normal and random.uniform  Outputs random values from 
# a normal distribution and uniform distribution respectively
# both allows us to set a seed to reproduce results in a predictible manner

rand_normal = tf.random.normal(
    [3,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

rand_uniform = tf.random.uniform(
    [2,2],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)


print(rand_normal)
print(rand_uniform)


tf.Tensor(
[[ 1.1011236   0.78853023  0.99086285]
 [-0.23330519  0.4722398   0.11457973]
 [-0.11979075 -1.8208897   1.36758   ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.45418787 0.02165043]
 [0.30716765 0.17651904]], shape=(2, 2), dtype=float32)


In [29]:
#Just like arrays, we can use indices/slices in Tensors.

tensor_indexed = tf.constant([1,2,3,4])
print(tensor_indexed[0])
print(tensor_indexed[1:3+1])

#Works for a n-Dimensional Tensors

#2D example
tensor_two_d = tf.constant([[1,2,0],
                            [6,-4,12],
                            [7,6,1],
                            [12,-14,6]])
print(tensor_two_d[1:2,0:3])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tf.Tensor([[ 6 -4 12]], shape=(1, 3), dtype=int32)


Created by Jhonatan Rivera Saumeth  - Based on the extraordinary course of freecodecamp.org [Deep Learning for Computer Vision](https://www.youtube.com/watch?v=IA3WxTTPXqQ)