Just as mentioned, Tensors represent an n-dimensional array, in that sense, you can represent a Tensor as a Vector, which means that you can use linear algebra operations to transform them.

In [1]:
import tensorflow as tf

tensor = tf.constant([1, -1, 2, 0])

# tf.abs Computes the absolute value of a tensor.
real_tensor_abs = tf.abs(tensor)
print(real_tensor_abs)

# Works with tensors that have complex elements
complex_tensor = tf.constant([-2.5 + 6.8j])
complex_tensor_abs = tf.abs(complex_tensor)
print(complex_tensor_abs)


tf.Tensor([1 1 2 0], shape=(4,), dtype=int32)
tf.Tensor([7.24499827], shape=(1,), dtype=float64)


In [13]:
# tf.add Returns x + y element-wise

# For Tensors that share dimensions works like vector addition
v1 = tf.constant([1, 2, 3, 4, 5])
v2 = tf.constant([4, 3, 2, 1, 0])

v_add_res = tf.add(v1, v2)
print(v_add_res)

# Multiplication is another option
v_mult_res = tf.multiply(v1, v2)
print(v_mult_res)

# Add/Multiply using a constant (scalar)
k = tf.constant([5])
v_add_k = tf.add(k, v1)
v_mult_k = tf.multiply(k, v1)
print(v_add_k)
print(v_mult_k)




tf.Tensor([5 5 5 5 5], shape=(5,), dtype=int32)
tf.Tensor([4 6 6 4 0], shape=(5,), dtype=int32)
tf.Tensor([ 6  7  8  9 10], shape=(5,), dtype=int32)
tf.Tensor([ 5 10 15 20 25], shape=(5,), dtype=int32)


In [ ]:
# Substract and Divide 
print(tf.subtract(v1, v2))
print(tf.divide(v1, v2))

# Safe division (takes care if you got a 0 in denominator)
float_v1 = tf.cast(v1,dtype=tf.float32)
float_v2 = tf.cast(v2,dtype=tf.float32)
print(tf.math.divide_no_nan(float_v1, float_v2))

#This multiplications create a Tensor with a shape of (3,5)
v3 = tf.constant([[7],[5],[3]])
print(v1.shape)
print(v3.shape)
print(tf.multiply(v1,v3))

In [20]:
# tf.math.argmax / tf.math.argmin
# Returns the index with the largest/shortest value across axes of a tensor.
x_argmax = tf.constant([1, 2, 10, 3, 4])
print(tf.argmax(x_argmax))
print(tf.argmin(x_argmax))


# Is posible to fix the axis
x_argmax_axis_fixed = tf.constant([[2, 20, 30, 3, 6], 
                        [3, 11, 16, 1, 8], 
                        [14, 45, 23, 5, 27]])

print(tf.argmax(x_argmax_axis_fixed, 0)) #"By cols"
print(tf.argmax(x_argmax_axis_fixed, 1)) #"By rows"


tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [35]:
# tf.math.equal Returns the truth value of (x == y) element-wise.x = tf.constant([2, 4])
t_equal_arg1 = tf.constant([2, 4])
t_equal_arg2 = tf.constant(2) # broadcasting to [2,2]
tf.math.equal(t_equal_arg1, t_equal_arg2) 


# tf.math.power Computes the power of one value to another.
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
print(tf.pow(x, y))  # [[256, 65536], [9, 27]]


#tf.math.reduce_sum Computes the sum of elements across dimensions of a tensor.
# reduce_sum_arg has a shape of (2, 3) (two rows and three columns):
reduce_sum_arg = tf.constant([[1, 2, 3], [1, 2, 3]])
print(reduce_sum_arg)
# sum all the elements
# 1 + 2 + 3 + 1 + 2 + 3 = 12
print(tf.reduce_sum(reduce_sum_arg))

#axis can be fixed
print(tf.reduce_sum(reduce_sum_arg, 0))
print(tf.reduce_sum(reduce_sum_arg, 1))


tf.Tensor(
[[  256 65536]
 [    9    27]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([6 6], shape=(2,), dtype=int32)


In [38]:
#tf.math.top_k returns the top k 
top_k_values = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=4)
print(top_k_values)


TopKV2(values=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([99, 98, 96,  4])>, indices=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5,  2,  9, 10])>)


Created by Jhonatan Rivera Saumeth  - Based on the extraordinary course of freecodecamp.org [Deep Learning for Computer Vision](https://www.youtube.com/watch?v=IA3WxTTPXqQ)